name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          # install project deps (including dev deps) using Poetry
          poetry install --no-interaction --no-ansi

          # ensure coverage is available inside the poetry virtualenv
          poetry run pip install --upgrade pip
          poetry run pip install coverage
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
